/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -c CarAdaptor -a car_adaptor_p.h:car_adaptor.cpp car.xml
 *
 * dbusxml2cpp is Copyright (C) 2008 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "alarmdbusadaptorp.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CarAdaptor
 */

AlarmDBusAdaptor::AlarmDBusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AlarmDBusAdaptor::~AlarmDBusAdaptor()
{
    // destructor
}

void AlarmDBusAdaptor::Alarm(int aEventId)
{
    // handle method call com.trolltech.Examples.CarInterface.accelerate
    QMetaObject::invokeMethod(parent(), "Alarm",Q_ARG(int, aEventId));
}


